### ISSUE TITLE
Request textDocument/hover failed

### ISSUE THREAD

**Issue by BenjaminHofstetter** [stardog-union/stardog-language-servers#47]
I am using vscode 1.66.1 and SPARQL Notebook Extension (vscode notebook https://marketplace.visualstudio.com/items?itemName=Zazuko.sparql-notebook) 

With the latest vscode version Stardog SPARQL Language Server starts to throw errors on the output console like this...

```
[Error - 11:33:52 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'getText')
  Code: -32603 
```

I don't know what changed in vscode and why this is happening now.

**Comment by anneeb** [comment]
Hi @BenjaminHofstetter,

I can confirm I’m seeing the same errors with the SPARQL Notebook Extension and VS Code 1.66.2. However, I do not see any problems with hover messages using our SPARQL language server ([github](https://github.com/stardog-union/stardog-vsc), [extension](https://github.com/stardog-union/stardog-language-servers/issues/47)) with a regular `.sparql` file.

I’m not extremely familiar with VS Code’s Notebook API, but I did try debugging our extension with some additional logs. It seems that the Notebook files are not triggering any `TextDocuments['onDidChangeContent']` events when they are opened or edited, which is correctly happening with the regular `.sparql` files. Additionally, I tried debugging the extension with a new notebook extension (setup with the [provided example serializer](https://code.visualstudio.com/api/extension-guides/notebook#serializer)), which surfaces the same errors.

I also tried all of the above with VS Code version 1.65.2 and I didn’t see the error logs in either the released extensions or my debugging environment. It looks to me that in that version, no interactions with or changes to the Notebook contents triggered any handlers within the language server. That is, the language server features are not enabled, thus there are no errors to show. 

I would recommend filing an issue with VSCode to confirm the expected behavior between a Notebook and language server.

**Comment by BenjaminHofstetter** [comment]
Thank you for your efforts. I raised an issue in vscode.

**Comment by dbaeumer** [comment]
@anneeb which version of the LSP libraries are you using ?

**Comment by dbaeumer** [comment]
The reason why I am asking is that VS Code changed the language selector code in 1.66 to accommodate notebooks better which I adapted in the latest version of the LSP libraries.

**Comment by anneeb** [comment]
Hi @dbaeumer, thanks for looking into this. I saw your comment in https://github.com/zazuko/vscode-sparql-notebook/issues/16#issuecomment-1117130584 about our extensions only supporting files using the file protocol.

I've opened an issue in our VS code extension repo instead for adding this support: https://github.com/stardog-union/stardog-vsc/issues/88
